ci: fail a pipeline when non-committed files have been found
Part of #13

diff --git a/.github/workflows/generate-python-app.yml b/.github/workflows/generate-python-app.yml
--- a/.github/workflows/generate-python-app.yml
+++ b/.github/workflows/generate-python-app.yml
@@ -23,5 +23,11 @@ jobs:
       - name: Generate Python + FastAPI application
         run: ../../src/cli.js --lang python
         working-directory: examples/python
-      - name: Check whether files were modified
-        run: git status --short
+      - name: Check whether all modified files have been committed
+        run: >-
+          MODIFIED_FILES="$(git status --short)"
+          if [ -n "$MODIFIED_FILES" ]; then
+            echo >&2 "ERROR: the following generated files have not been committed:"
+            echo >&2 "$MODIFIED_FILES"
+            exit 1
+          fi
