ci: add semicolons to make shell commands work with >- YAML notation
Correction for df22aa2e76bdbb2e3b3103e0865026c304a417f8 commit.

Part of #13

diff --git a/.github/workflows/generate-python-app.yml b/.github/workflows/generate-python-app.yml
--- a/.github/workflows/generate-python-app.yml
+++ b/.github/workflows/generate-python-app.yml
@@ -25,9 +25,9 @@ jobs:
         working-directory: examples/python
       - name: Check whether all modified files have been committed
         run: >-
-          MODIFIED_FILES="$(git status --short)"
+          MODIFIED_FILES="$(git status --short)";
           if [ -n "$MODIFIED_FILES" ]; then
-            echo >&2 "ERROR: the following generated files have not been committed:"
-            echo >&2 "$MODIFIED_FILES"
-            exit 1
+            echo >&2 "ERROR: the following generated files have not been committed:";
+            echo >&2 "$MODIFIED_FILES";
+            exit 1;
           fi
